# Generated by Django 5.0 on 2025-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Used to link records for longitudinal view', max_length=255, verbose_name='patient ID')),
                ('patient_data', models.JSONField(verbose_name='patient data')),
                ('debate_history', models.JSONField(default=list, verbose_name='debate history')),
                ('final_report', models.JSONField(blank=True, null=True, verbose_name='final report')),
                ('differential_diagnoses', models.JSONField(default=list, verbose_name='differential diagnoses')),
                ('selected_specialists', models.JSONField(default=list, verbose_name='selected specialists')),
                ('follow_up_history', models.JSONField(default=list, verbose_name='follow-up history')),
                ('detected_medications', models.JSONField(blank=True, null=True, verbose_name='detected medications')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(default=list, verbose_name='tags')),
                ('final_diagnosis', models.TextField(verbose_name='final diagnosis')),
                ('outcome', models.TextField(blank=True, verbose_name='outcome')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='is anonymous')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'case library entry',
                'verbose_name_plural': 'case library entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMETopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500, verbose_name='topic')),
                ('relevance', models.TextField(verbose_name='relevance')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CME topic',
                'verbose_name_plural': 'CME topics',
                'ordering': ['-created_at'],
            },
        ),
    ]
