# Generated by Django 5.0 on 2025-11-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='caselibrary',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_library_entry', to='analyses.analysis', verbose_name='analysis'),
        ),
        migrations.AddField(
            model_name='cmetopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cme_topics', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', '-created_at'], name='analyses_an_user_id_bca6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['patient_id'], name='analyses_an_patient_a24198_idx'),
        ),
    ]
